blood/urls.py
from django.conf.urls import url
from blood import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    # ex: /polls/5/
	
    url(r'^view_request_thanks/(?P<requestID>\S+)/$',views.view_request_thanks,name='view_request_thanks'),
    url(r'^view_request/(?P<requestID>\S+)/$',views.view_request,name='view_request'),
    url(r'^requestblood_form/$',views.requestblood_form,name='requestblood_form'),
    url(r'^requestblood_thanks/$',views.requestblood_thanks,name='requestblood_thanks'),
    url(r'^donate_blood/$', views.donate_blood, name='donate_blood'),
    url(r'^donateblood_thanks/$',views.donateblood_thanks,name='donateblood_thanks'),
    url(r'^donor_list/$',views.donor_list,name='donor_list'),
    url(r'^send_email1/$',views.send_email1,name='send_email1'),
    url(r'^bloodcamp_list/$',views.bloodcamp_list,name='bloodcamp_list'),
	url(r'^main/$',views.main, name='main'),
    url(r'^bloodcamp/$',views.bloodcamp,name='bloodcamp'),
    url(r'^camps_detail/$',views.camps_detail,name='camps_detail'),
    url(r'^camp_donate/(?P<campID>\S+)$',views.camp_donate,name='camp_donate'),
    url(r'^bloodcamp_form/$',views.bloodcamp_form,name='bloodcamp_form'),
    url(r'^bloodcamp_form_thanks/$',views.bloodcamp_form_thanks,name='bloodcamp_form_thanks'),

    url(r'^drive_list/(?P<driveID>\S+)/$',views.drive_list,name='drive_list'),
    url(r'^camp_post/(?P<campID>\S+)/$',views.camp_post,name='camp_post'),
    url(r'^store_camp_post/(?P<campID>\S+)/$',views.store_camp_post,name='store_camp_post'),
 

    url(r'^drive/$', views.drive, name='drive'),

    url(r'^donor/$', views.donor, name='donor'),
    url(r'^hospital/$', views.hospital, name='hospital'),
    url(r'^recepient/$', views.recepient, name='recepient'),
    url(r'^camp/$', views.camp, name='camp'),
    url(r'^link/$', views.link, name='link'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^share/$', views.share, name='share'),
    url(r'^view_story/(?P<story_id>\S+)/$', views.view_story, name='view_story'),
    url(r'^putstory/$',views.putstory,name='putstory'),
    url(r'^putstory_thanks/$',views.putstory_thanks,name='putstory_thanks'),
	url(r'^faqs/$',views.faqs,name='faqs'),
	url(r'^feedback/$',views.feedback,name='feedback'),
	url(r'^contact/$',views.contact,name='contact'),
	url(r'^about/$',views.about,name='about'),
	url(r'^home/$',views.home,name='home'),
	url(r'^todaycamp/$',views.todaycamp,name='todaycamp'),
]

sigegov/urls.py
from django.conf.urls import patterns, include, url
from sigegov import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^authorize_user/(?P<userID>\S+)/$',views.authorize_user,name='authorize_user'),
    url(r'^user_details/(?P<userID>\S+)/$',views.user_details,name='user_details'),
    url(r'^objectives/$',views.objectives,name='objectives'),
    url(r'^executive_committee/$',views.executive_committee,name='executive_committee'),
    url(r'^not_authorized/$',views.not_authorized,name='not_authorized'),
    url(r'^view_publication/(?P<pubID>\S+)/$',views.view_publication,name='view_publication'),
    url(r'^process_upvote/(?P<pubID>\S+)/$',views.process_upvote,name='process_upvote'),
    url(r'^process_downvote/(?P<pubID>\S+)/$',views.process_downvote,name='process_downvote'),
    url(r'^view_statewise/$',views.view_statewise,name='view_statewise'),
    url(r'^publications/$',views.publications,name='publications'),
    url(r'^publications/(?P<stateID>[\S\ ]+)/$',views.publications,name='publications'),
    url(r'^send_email_sigegov/(?P<page_path>\S+)/$',views.send_email_sigegov,name='send_email_sigegov'),
    url(r'^enter_data/$',views.enter_data,name='enter_data'),
    url(r'^create_event/$',views.create_event,name='create_event'),
    url(r'^show_event/$',views.show_event,name='show_event'),
    url(r'^download/(?P<file_name>\S+)/$',views.download,name='download'),
    url(r'^compare_publications/(?P<pubId_list>\S+)/$',views.compare_publications,name='compare_publications'),
    url(r'^members/$',views.members,name='members'),
    url(r'^pdfopen/(?P<pdf_id>\S+)/$',views.pdfopen,name='pdfopen'),

    url(r'^view_request_thanks/(?P<requestID>\S+)/$',views.view_request_thanks,name='view_request_thanks'),
    url(r'^view_request/(?P<requestID>\S+)/$',views.view_request,name='view_request'),
    url(r'^requestblood_form/$',views.requestblood_form,name='requestblood_form'),
    url(r'^requestblood_thanks/$',views.requestblood_thanks,name='requestblood_thanks'),
    url(r'^donate_blood/$', views.donate_blood, name='donate_blood'),
    url(r'^donateblood_thanks/$',views.donateblood_thanks,name='donateblood_thanks'),
    url(r'^donor_list/$',views.donor_list,name='donor_list'),
    url(r'^send_email1/$',views.send_email1,name='send_email1'),
    url(r'^bloodcamp_list/$',views.bloodcamp_list,name='bloodcamp_list'),
	url(r'^main/$',views.main, name='main'),
    url(r'^bloodcamp/$',views.bloodcamp,name='bloodcamp'),
    url(r'^camps_detail/$',views.camps_detail,name='camps_detail'),
    url(r'^camp_donate/(?P<campID>\S+)$',views.camp_donate,name='camp_donate'),
    url(r'^bloodcamp_form/$',views.bloodcamp_form,name='bloodcamp_form'),
    url(r'^bloodcamp_form_thanks/$',views.bloodcamp_form_thanks,name='bloodcamp_form_thanks'),

    url(r'^drive_list/(?P<driveID>\S+)/$',views.drive_list,name='drive_list'),
    url(r'^camp_post/(?P<campID>\S+)/$',views.camp_post,name='camp_post'),
    url(r'^store_camp_post/(?P<campID>\S+)/$',views.store_camp_post,name='store_camp_post'),
 

    url(r'^drive/$', views.drive, name='drive'),

    url(r'^donor/$', views.donor, name='donor'),
    url(r'^hospital/$', views.hospital, name='hospital'),
    url(r'^recepient/$', views.recepient, name='recepient'),
    url(r'^camp/$', views.camp, name='camp'),
    url(r'^link/$', views.link, name='link'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^share/$', views.share, name='share'),
    url(r'^view_story/(?P<story_id>\S+)/$', views.view_story, name='view_story'),
    url(r'^putstory/$',views.putstory,name='putstory'),
    url(r'^putstory_thanks/$',views.putstory_thanks,name='putstory_thanks'),
	url(r'^faqs/$',views.faqs,name='faqs'),
	url(r'^feedback/$',views.feedback,name='feedback'),
	url(r'^contact/$',views.contact,name='contact'),
	url(r'^about/$',views.about,name='about'),
	url(r'^home/$',views.home,name='home'),
	url(r'^todaycamp/$',views.todaycamp,name='todaycamp'),
	url(r'^autocomplete/$',views.autocomplete,name='autocomplete'),
    url(r'^search/$',include('haystack.urls')),
]

test1/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'test1.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r"^$", 'sigegov.views.main'),
    url(r'^sigegov/', include('sigegov.urls')),
    url(r'^chat/', include('djangoChat.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'', include('social_auth.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

sigegov/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import signals
from django.db.models.signals import post_save
from django.dispatch import receiver
from vote.managers import VotableManager

class UserProfile(models.Model):
	    #required by the auth model
	user = models.ForeignKey(User, unique=True)
	status = models.IntegerField(default=0)
#url = models.URLField()
#home_address = models.TextField()

class Event(models.Model):
	event=models.TextField()
	organiser=models.TextField()
	attachment = models.FileField(upload_to='events/%Y/%m/%d',blank=True)

class Publications(models.Model):
	votes = VotableManager(blank=True)
	document_id = models.TextField(blank=True)
	project_title = models.TextField(blank=True)
	department_name = models.TextField(blank=True)
	name_1 = models.TextField(blank=True)
	designation_1 = models.TextField(blank=True)
	email_1 = models.TextField(blank=True)
	address_1 = models.TextField(blank=True)
	phone_1 = models.TextField(blank=True)
	fax_1 = models.TextField(blank=True)
	mobile_1 = models.TextField(blank=True)
	name_2 = models.TextField(blank=True)
	designation_2 = models.TextField(blank=True)
	email_2 = models.TextField(blank=True)
	address_2 = models.TextField(blank=True)
	phone_2 = models.TextField(blank=True)
	fax_2 = models.TextField(blank=True)
	mobile_2 = models.TextField(blank=True)
	category = models.TextField(blank=True)
	nature = models.TextField(blank=True)
	description = models.TextField(blank=True)
	date = models.TextField(blank=True)
	url = models.TextField(blank=True)
	business_model = models.TextField(blank=True)
	no_process = models.TextField(blank=True)
	beneficiary_1 = models.TextField(blank=True)
	beneficiary_2 = models.TextField(blank=True)
	beneficiary_3 = models.TextField(blank=True)
	transaction = models.TextField(blank=True)
	benefit_1 = models.TextField(blank=True)
	benefit_2 = models.TextField(blank=True)
	benefit_3 = models.TextField(blank=True)
	process_1 = models.TextField(blank=True)
	process_2 = models.TextField(blank=True)
	process_3 = models.TextField(blank=True)
	database = models.TextField(blank=True)
	operating = models.TextField(blank=True)
	web_server = models.TextField(blank=True)
	prime_agency = models.TextField(blank=True)
	network_arrangement = models.TextField(blank=True)
	datacenter = models.TextField(blank=True)
	csc = models.TextField(blank=True)
	formal_document = models.TextField(blank=True)
	implementation = models.TextField(blank=True)
	no_training = models.TextField(blank=True)
	sector = models.TextField(blank=True)
	sub_sector = models.TextField(blank=True)
	state = models.TextField(blank=True)	
	attachment = models.FileField(upload_to='%Y/%m/%d',blank=True)

class Recepient(models.Model):
	user = models.ManyToManyField(User)
   	name=models.CharField(max_length=200)
	address=models.CharField(max_length=200)
	contact=models.CharField(max_length=10)
	bggroup=models.CharField(max_length=2)
	email=models.CharField(max_length=100)
	bgunits=models.IntegerField(blank=True)
	age=models.IntegerField(blank=True)
	lat1=models.FloatField(blank=True,null=True)
	long1=models.FloatField(blank=True,null=True)

class Donor(models.Model):
	user = models.ManyToManyField(User)
	name=models.CharField(max_length=200)
	address=models.CharField(max_length=200)
	contact=models.CharField(max_length=10)
	bggroup=models.CharField(max_length=2)
	email=models.CharField(max_length=100)
	bgunits=models.IntegerField(blank=True)
	age=models.IntegerField(blank=True)
	lat1=models.FloatField(blank=True,null=True)
	long1=models.FloatField(blank=True,null=True)

class Hospital(models.Model):
	contact=models.CharField(max_length=10)
	address=models.CharField(max_length=200)
	name=models.CharField(max_length=200)
	abgroup=models.CharField(max_length=200)

class Camp(models.Model):
	name=models.CharField(max_length=200)
	email=models.CharField(max_length=100)
	contact=models.CharField(max_length=10)
	address=models.CharField(max_length=200)	
	uid=models.IntegerField()
	cdate = models.CharField(max_length=200)
	sdate=models.CharField(max_length=200)
	edate=models.CharField(max_length=200)
	lat1=models.FloatField(blank=True,null=True)
	long1=models.FloatField(blank=True,null=True)

class Link(models.Model):
	uid=models.IntegerField()
	cid=models.IntegerField()
	guser=models.CharField(max_length=200)
	flag=models.IntegerField(blank=True)

class Post(models.Model):
	uid = models.IntegerField()
	#user=models.ForeignKey(User)
	comment=models.CharField(max_length=200)
	campid=models.CharField(max_length=200)

class Story(models.Model):
	suser = models.ManyToManyField(User)
	story=models.CharField(max_length=200)
	tag=models.CharField(max_length=200)
	#pic=models.ImageField(upload_to="static",blank=True)

class Notification(models.Model):
	did = models.ManyToManyField(User)
	#did=models.ForeignKey(User)
	rid=models.CharField(max_length=200)
	flag=models.IntegerField(blank=True)

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

class Choice(models.Model):
	question = models.ManyToManyField(Question)
    	#question = models.ForeignKey(Question)
    	choice_text = models.CharField(max_length=200)
    	votes = models.IntegerField(default=0)

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
	# Creates user profile
	if created:
		profile, new = UserProfile.objects.get_or_create(user=instance)

sigegov/forms.py
from haystack.forms import SearchForm
from django import forms
class PublicationsSearchForm(SearchForm):
	def no_query_found(self):
		return self.searchqueryset.all()

class UploadEventForm(forms.Form):
	event = forms.CharField(max_length=50)
	organiser = forms.CharField(max_length=50)
	attachment = forms.FileField()
	

sigegov/templates/sigegov/create_event.html
{% extends "sigegov/base.html" %}
{% load i18n %}
{% block title %}Create Event{% endblock %}

{% block content-body %}
<form id="eventForm" method="post" class="form-horizontal" action="/sigegov/create_event/" enctype="multipart/form-data"                    data-bv-feedbackicons-valid="glyphicon glyphicon-ok"
	data-bv-feedbackicons-invalid="glyphicon glyphicon-remove"
	data-bv-feedbackicons-validating="glyphicon glyphicon-refresh">{% csrf_token %}

	<div class="form-group">
	<label class="col-lg-3 control-label">Name of the Event:</label>
	<div class="col-lg-5">
		<input id="id_event" type="text" class="form-control" name="event"
		data-bv-notempty="true"
		data-bv-notempty-message="Name is required and cannot be empty"/>
	</div>	
	</div>

	<div class="form-group">
	<label class="col-lg-3 control-label">Name of organiser:</label>
	<div class="col-lg-5">
		<input id="id_organiser" type="text" class="form-control" name="organiser"
		data-bv-notempty="true"
		data-bv-notempty-message="Name is required and cannot be empty"/>
	</div>	
	</div>

	<div class="form-group">
	<label class="col-lg-3 control-label">Upload File:</label>
	<div class="col-lg-5">
		<input id="id_attachment" type="file" class="form-control" name="attachment" size="10000"
		data-bv-notempty="true"
		data-bv-notempty-message="Name is required and cannot be empty"/>
	</div>	
	</div>

	<div class="form-group">
		<div class="col-lg-9 col-lg-offset-3">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
	</div>
</form>
{% endblock %}

sigegov/templates/sigegov/enter.html
{{value}}

sigegov/templates/sigegov/executive_committee.html
{% extends "sigegov/base.html" %}
{% load i18n %}
{% block title %}Executive Committee{% endblock %}
{% block content-body %}
<h1 align = "center"> Executive Commitee </h1>
<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').dataTable();
			} );
		</script>

		<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>S.No</th>
                <th>Members</th>
		<th>Contact Address</th>
		<th>EmailID</th>
		<th>Phone No</th>                
            </tr>
        </thead>
        <tbody>
		<tr>
			<td>01</td>
			<td>Dr Ashok K Agarwal,</td>
			<td>Dr Ashok agarwal 
Adjunct professor BITS Pilani
Chairman EWB India</td>
			<td>agarwal.ashok.k@gmail.com</td>
			<td>+91 9848053024</td>	
		</tr>
		<tr>
			<td>02</td>
			<td>Prof MP Gupta</td>
			<td>Department of Management Studies, IIT, Delhi
Vishwakarma Bhawan, 
Shahid Bhagat Singh Marg
New Delhi – 110 016</td>
			<td>mpgupta@dms.iitd.ac.in</td>
			<td>+91 9811027530</td>	
		</tr>
		<tr>
			<td>03</td>
			<td>Mr. Piyush Gupta
(Chairman, CSI SIG)</td>
			<td>Asst Vice President (Capacity Building & Knowledge Management; National Institute for Smart Government (NISG YSR Bhavan, Financial District, Nanakramguda, Rajendra Nagar, Hyderabad -500 032, India</td>
			<td>piyush.gupta@nisg.org</td>
			<td>+91 98499-14466</td>
		</tr>
		<tr>
			<td>04</td>
			<td>Prof ML Saikumar</td>
			<td>Head, IT Division & PGDBM Coordinator
Institute of Public Enterprise
Osmania University Campus
Hyderabad – 500 007</td>
			<td>saikumar@ipeindia.org</td>
			<td>(040) 27095182 +91 9849126019</td>
		</tr>
		<tr>
			<td>05</td>
			<td>Dr. Nityesh Bhatt</td>
			<td>Sr. Associate Professor – IT Area
Institute of Management
Nirma University of Science & Technology, Gandhinagar – Sarkhej Highway 
Ahmedabad – 382481</td>
			<td>nityesh@imnu.ac.in
nityeshb@gmail.com</td>
			<td>(02717)-241900-04
Ext: 634
Mob: 99743-31833</td>
		</tr>
		<tr>
			<td>06</td>
			<td>Prof. Sanjiv Vaidya</td>
			<td>Professor – MIS
Indian Institute of Management
Diamond Harbour Road 
Joka, Kolkata (Calcutta) - 700104 
West Bengal, INDIA</td>
			<td>
sdvaidya@iimcal.ac.in</td>
			<td>(033)-2467 8300
Ext: 414
Mob:92316-83276</td>
		</tr>
		<tr>
			<td>07</td>
			<td>Mr. Suresh Chanda</td>
			<td>Commissioner, Commissionerate of Commercial Taxes
Kattelamandi, Abids, Hyderabad</td>
			<td>commissioner_cct@ap.gov.in</td>
			<td>(040)-23456409 (040)- 24602171</td>
		</tr>
		<tr>
			<td>08</td>
			<td>Maj. Gen (Retd)
Dr. RK Bagga
Past Chairman, SIGeGOV</td>
			<td>Advisor IIIT-H, Gachibowli
Hyderabad – 500 032</td>
			<td>rbagga@iiit.ac.in</td>
			<td>+91 9849251716</td>
		</tr>
		<tr>
			<td>09</td>
			<td>Dr. Mahesh Chandra</td>
			<td>Deputy Director General,
National Informatics Centre
Ministry of Communication & Information Technology
A-Block, CGO Complex, Lodhi Road, New Delhi – 110 003</td>
			<td>mcchandra@nic.in</td>
			<td>(011)-24364635</td>
		</tr>
		<tr>
			<td>10</td>
			<td>Mr. Minoo Dastur</td>
			<td>Executive Director
Nihilent Technologies Pvt.Ltd.,
4th Floor, Weikfiedl IT Citi Infopark,
Nagar Road,
Pune 411 014</td>
			<td>m.dastur@nihilent.com</td>
			<td>(020) 3984 6100</td>
		</tr>
		<tr>
			<td>12</td>
			<td>Prof Harish Iyer 
Convener 
CSI Nihilent e-Gov Awards 2012-13</td>
			<td>397, Old MIG Phase I 
BHEL Ramachandrapuram 
Hyderabad 502032</td>
			<td>pharishiyer@gmail.com</td>
			<td>098481 48192</td>
		</tr>
		<tr>
			<td>13</td>
			<td>Dr Akshai agarwal</td>
			<td>VC Gujarat Technological University 
LD College of Engg Campus 
Navrang pura 
Ahmedabad 380015</td>
			<td>vc@gtu.ac.in</td>
			<td>079-26300699 
079-26300499/599</td>
		</tr>
		<tr>
			<td>14</td>
			<td>Mr Satish Babu</td>
			<td>President,
InApp Information Technologies
Technopark, Trivandrum – 695 581</td>
			<td>sb@inapp.com</td>
			<td>094470-27274
Tel: (471) 252 7270</td>
		</tr>
		<tr>
			<td>15</td>
			<td>S Kapoor 
Past Convener-CSI Nihilent eGov Awards</td>
			<td>551/2, Mansarovar Heights 1 
Mano Vikas Nagar P.O. Secunderbad 500009</td>
			<td>kapoorsurendra@yahoo.com</td>
			<td>+91 939 101 3432
+91 40 2799 3196</td>
		</tr>
		<tr>
			<td>16</td>
			<td>GSN Prabhu</td>
			<td>H No. 1 - 98/4/61, 
Plot 61, 
Arunodaya Colony, Madhapur, 
Hyderabad : 500081</td>
			<td>gsnprabhu@yahoo.com</td>
			<td>98499-83946</td>
		</tr>
		<tr>
			<td>17</td>
			<td>Ms A Sridevi 
Joint Convener
CSI Nihilent e-Gov Awards 2012-13</td>
			<td>Manager, National Institute for Smart Government (NISG) 
YSR Bhavan, Financial District, Nanakramguda, Rajendra Nagar, Hyderabad -500 032, India</td>
			<td>ayaluri.sridevi@nisg.org</td>
			<td>040-6654 5352
98662-48887</td>
		</tr>
		

	</tbody>
</table>
{% endblock %}

sigegov/templates/sigegov/home.html
{% extends 'sigegov/base.html' %}
{% block content %}
<head>

</head>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">

    <div class="item active">
      <img src="http://baq.kz/foto/01fb9e5586eec135656975b46991485f.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="http://www.egov.gov.sg/image/image_gallery?uuid=038fa720-4fd5-4373-a187-45c1e30d93e2&groupId=10157&t=1341934967258" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br/>
<div>
<h2>SIG on eGovernance</h2>
<p >
Computer Society of India ( CSI ), has implemented the concept of “Special Interest Groups” to promote activities and research in few focused areas. Special Interest Group on e-Governance ( SIGeGov) has been formed accordingly. The basic objective has been to focus on an important area where Information Technology can be leveraged and bring like minded professionals together to add value by bringing out recommendations relevant to various stake holders.

India has already established itself as a leader in the Information Technology sector and create research echo system in the country in this area. Governments are under pressure to deliver a range of services in a timely, efficiently, economical, equitable, and transparent and corruption free manner to its citizens. E-Governance can have a profound impact on the poor and ultimately on the economic output and growth of the country as a whole. Information acts as a revolutionary force in bridging the digital divide. IT can vastly extend access to education, health care, financial services, vocational skills, administrative services and other aspects of the modern society, to many more people at far lower costs apart from generating employment. IT can dramatically reduce the cost of communications; improve access to technology and marketing capabilities for the rural poor. It can help in eliminating intermediary exploitation in the production and distribution chains, increasing government accountability.

The last decade has witnessed e-Governance penetrating India in both Urban and Rural areas, Central Government has announced a National e-Governance plan (NEGP) and each State has also defined their own e-Governance policies within the frame work of NEGP. The total investments being made to implement these initiatives are huge, and are impacting the domestic ICT market as well as education and training area significantly. IT spending in our country is being driven primarily by this initiative and impacting the lives of ordinary citizen across the country in a very positive fashion.

CSI is the only professional society covering individual user / Citizens as members and is most appropriately suited to focus and add significant value to the successful implementation of the e-Governance initiative in our country.

e-Governance has the capacity to take our country to the next generation and CSI-SIG-eGov plans to play a important role in that process.
</p>
</div>

{% endblock %}

sigegov/templates/sigegov/members.html
{% extends "sigegov/base.html" %}
{% load i18n %}
{% block title %}Members{% endblock %}
{% block content-body %}

<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').dataTable();
			} );
		</script>

		<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>                
            </tr>
        </thead>
 
        <tbody>
           
{% for i in members %}
		<tr>
			<th>{{i}}</th>
			<th>{{i.email}}</th>
		</tr>
{% endfor %}

</tbody>
</table>
{% endblock %}

sigegov/templates/sigegov/not_authorized.html
{% extends 'sigegov/base.html' %}
{% load i18n %}
{% block title %}Unauthorized{% endblock %}

{% block content-body %}
<h1> You are not authorized to view this page </h1>
{% endblock %}